image: node:18

stages:
  - build
  - deploy

variables:
  DOCKER_HOST: "unix:///var/run/docker.sock"  # Docker sock üzerinden bağlantı

build:
  stage: build
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - dist/

deploy:
  stage: deploy
  script:
    - docker stop kubysisfrontend || true
    - docker rm kubysisfrontend || true
    - docker build -t kubysisfrontend:latest .
    - docker run -d --name kubysisfrontend -p 3000:80 kubysisfrontend:latest
