image: node:18

stages:
  - build
  - deploy

variables:
  DOCKER_HOST: "unix:///var/run/docker.sock"  # Docker sock üzerinden bağlantı

build:
  stage: build
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - dist/

deploy:
  stage: deploy
  image: docker:stable
  script:
    - docker stop kubysisfrontend || true
    - docker rm kubysisfrontend || true
    - docker build -t kubysisfrontend:latest .
    - docker run -d --name kubysisfrontend -p 3000:80 --network nginxproxymanager_default --volume shared_app:/app/shared kubysisfrontend:latest
    - docker exec -i kubysisfrontend sh -c "find /app -mindepth 1 -not -path '/app/shared*' -exec mv {} /app/shared/ \;"
